### ISSUE TITLE
预读取似乎只支持超链接里面的文字。。。

### ISSUE THREAD

**Issue by matocool** [syhyz1990/instantpage#14]
预读取似乎只支持超链接里面的文字。。。

是这样的，我打开搜狐门户。还有贴吧之类的。。把指针放到好几个超链接上面。

发现火绒自带的的网速上下行的悬浮窗，只显示下载了几十KB的流量

点进去之后，才会有几兆的下行速度。。。

似乎这个预读取只支持连接内的文字吗，不支持预读里面的图片以及其余元素。。

不过感觉预读取功能还是有效的，打开网页都是秒开，还是感谢大佬的作品

**Comment by syhyz1990** [comment]
浏览器的特性不支持预读取图片等其他资源，只能是超链接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 上午6:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/instantpage] 预读取似乎只支持超链接里面的文字。。。 (Issue #14)




 
预读取似乎只支持超链接里面的文字。。。
 
是这样的，我打开搜狐门户。还有贴吧之类的。。把指针放到好几个超链接上面。
 
发现火绒自带的的网速上下行的悬浮窗，只显示下载了几十KB的流量
 
点进去之后，才会有几兆的下行速度。。。
 
似乎这个预读取只支持连接内的文字吗，不支持预读里面的图片以及其余元素。。
 
不过感觉预读取功能还是有效的，打开网页都是秒开，还是感谢大佬的作品
