### ISSUE TITLE
感谢大佬，很好用。可否做到全局加速呢？

### ISSUE THREAD

**Issue by matocool** [syhyz1990/instantpage#4]
我32G内存，我根本不在乎预读所占用的内存。

其次如果可以做到全局预读（除退出 保存 等关键词之类的）会不会更方便？

**Comment by matocool** [comment]
现在很多网页都是按需加载，尤其是 视频网站 这种网页比较长的网页。  

向下拉的时候才会读取网页内容。  如果能提前在后台不断的请求读取，那么向下滚动网页的时候就会很丝滑，很顺 没有卡顿的感觉。

图1 是 打开优酷之后没有向下滚动

图2 是 打开优酷之后完全向下滚动完毕

如果我们需要向下滚动，就会出现读取网页内容从而产生延迟时间。体验肯定不如完全预读。

![855a04805f9e3a4ca7b3eb10609ee315_t013db2d3e9e2e90cc5](https://user-images.githubusercontent.com/83129369/157860859-64aeba88-98d5-4edf-a255-507fc675b6d9.png)
![78959852ac0934f420fa40a1642c8746_t01ead7d71b541b63b7](https://user-images.githubusercontent.com/83129369/157860878-a6c85021-eec5-40dc-9e6e-8aea21ecbfb9.jpg)

**Comment by syhyz1990** [comment]
这个做不到，下滑加载一般是JS代码里控制的。预读取只支持超链接

**Comment by matocool** [comment]
> 

谢谢大佬
