### ISSUE TITLE
有没有可能做一个对视频完全加速的可能？

### ISSUE THREAD

**Issue by matocool** [syhyz1990/instantpage#5]
比如我在某视频网站看一个视频，全场假设2小时。

比如我想跳过 拖到某处，那么必然会产生一定的延迟。

可否开发一个插件，在后台模拟不断地预读，把整个视频的缓存丢到内存里面。

这样就跟在本地看电影一样做到拉到无延迟。

谢谢~

**Comment by syhyz1990** [comment]
这个做不到，哈哈
