### ISSUE TITLE
大佬，插件似乎不支持 so.com

### ISSUE THREAD

**Issue by matocool** [syhyz1990/instantpage#7]
暂时发现 so.com无效，别的网站有效。请大佬排查

册了好几个网页，暂时就是so无效。。百度有效

加速链接已打开，

![image](https://user-images.githubusercontent.com/83129369/160043158-9451720f-ee52-4fcc-a7f0-f236ce683459.png)

![image](https://user-images.githubusercontent.com/83129369/160043356-dd560d9a-3f67-4353-a662-9137fd5fc741.png)

**Comment by bhzzh** [comment]
你好

**Comment by bhzzh** [comment]
你好

**Comment by matocool** [comment]
> 你好

你好？

**Comment by bhzzh** [comment]
你的软件还更新吗

**Comment by syhyz1990** [comment]
360浏览器不允许 so.com 运行任何扩展，包括 Tampermonkey 和 各种广告过滤插件。

**Comment by bhzzh** [comment]
是不是还得更新？

**Comment by bhzzh** [comment]
我是说谷歌。插件。

**Comment by syhyz1990** [comment]
360浏览器禁止了在这个域名下的所有扩展,包括tampermonkey adblock 。你用别的浏览器就正常。这属于360的骚操作。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月25日(周五) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/instantpage] 大佬，插件似乎不支持 so.com (Issue #7)




 
暂时发现 so.com无效，别的网站有效。请大佬排查
