### ISSUE TITLE
> 你好

### ISSUE THREAD

**Issue by bhzzh** [syhyz1990/instantpage#8]
> 你好

你好？

_Originally posted by @matocool in https://github.com/syhyz1990/instantpage/issues/7#issuecomment-1088294062_

**Comment by matocool** [comment]
嗯？？？

**Comment by bhzzh** [comment]
大约什么时候更新呢？

**Comment by matocool** [comment]
> 大约什么时候更新呢？

更新啥。。更新哪个？
